### ISSUE TITLE
Styling of the COM port Pop-up window

### ISSUE THREAD

**Issue by cgardnermccune** [STEM-C/CaSMM#42]
If possible, it would be great to style the COM port Pop-up window that asks the user to select the USB port. This will ensure that it looks like a feature of the software and not an error.

<img width="721" alt="Screen Shot 2020-07-08 at 12 09 18 PM" src="https://user-images.githubusercontent.com/9022220/88235589-2d206c80-cc49-11ea-9b67-8c7a000445f4.png">

**Comment by rennemannd** [comment]
As far as I am aware this is impossible since it is a security concern with chrome, however we can look more into it to make sure that is the case. A more realistic option would be to limit what is shown in the pop up to only display the arduino board which is possible.

**Comment by nionata** [comment]
It may also be possible to preselect the port and board. This could possibly solve the issue of having that popup.

**Comment by nionata** [comment]
[avrgirl-arduino docs](https://github.com/noopkat/avrgirl-arduino#how-do-i-use-it)

- [ ] Create a port selecter/dropdown
- [ ] On workspace load, try to select the arduino port
```
Avrgirl.list(function(err, ports) {
  console.log(ports);
  /*
  [ { comName: '/dev/cu.usbmodem1421',
  	   manufacturer: 'Arduino (www.arduino.cc)',
      serialNumber: '55432333038351F03170',
      pnpId: '',
      locationId: '0x14200000',
      vendorId: '0x2341',
      productId: '0x0043',
      _standardPid: '0x0043' } ]
  */
});
```
- [ ] Change the `compileArduinoCode` function to accept the port selection and us it here [here](https://github.com/STEM-C/STEM-C/blob/develop/client/src/views/Workspace/helpers.js#L54)
```
var avrgirl = new Avrgirl({
  board: 'uno',
  port: '/dev/cu.usbmodem1412'
});
```

**Comment by tamargoadam** [comment]
Much of the functionality from this module, such as specifying port and listing available USB devices, is not available or working, likely due to the fact that the full module is not being used.

These actions are critical for implementing a customized port pop-up or avoiding the pop-up all together, with the use of the avrgirl-arduino module. For this reason we will probably need to build the necessary functionality out manually, rather than working through the avrgirl-arduino module
